apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxrecreate
  namespace: devopstraining
  labels:
    app: nginx
spec:
  replicas: 5
  minReadySeconds: 1 # seconds new pod should be ready to be considered healthy
  progressDeadlineSeconds: 60 # seconds to wait before reported stalled deploy
  revisionHistoryLimit: 5 # no. of replicasets that can be rolled back-default10
  strategy:
    type: Recreate # default, other option is "Recreate"-req downtime
  selector:
    matchLabels:
      app: nginxrecreate
  template:
    metadata:
      labels:
        app: nginxrecreate
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"  # 128 MB
            cpu: "100m" # 100 millicpu (10% of cpu)
