apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-svc
  labels:
    app: ss
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ss
  template:
    metadata:
      labels:
        app: ss
    spec:
      containers:
      - name: ss
        image: mhausenblas/simpleservice:0.4.0
        ports:
        - containerPort: 9876
