apiVersion: v1
kind: Service
metadata:
  labels:
    name: lb-simple-service
    name: ss
  name: simple-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9876
  selector:
    app: ss
