apiVersion: v1
kind: Service
metadata:
  labels:
    name: node-port-simple-service
    name: ss
  name: simple-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9876
      nodePort: 30080
  selector:
    app: ss
